name: HelpBook
author: JarJarBings12
version: 1.2.43

main: ch.JarJarBings12.helpbook.Core.Core

commands: 
    HelpBook: 
       usage: /<commands> 
       description: Mute the Chat global 
       
permissions:
  helpbook.*:
    description: Allows access to all commands.
    children:
      helpbook.helpbook: true
      helpbook.helpbook.admin: true
      helpbook.helpbook.admin.setTitle: true
      helpbook.helpbook.admin.setAuthor: true
      helpbook.helpbook.admin.setBookAtSlot: true
      helpbook.helpbook.admin.setWindowName: true
      helpbook.helpbook.admin.turnmode: true
      helpbook.helpbook.info: true