name: HelpBoook
author: JarJarBings12
version: 1.0.0

main: ch.JarJarBings12.helpbook.Core.Core

commands: 
    HelpBook: 
       usage: /<commands> 
       description: Mute the Chat global 
